services:
  postgres:
    image: postgres:15-alpine
    container_name: lms_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lms_db
    ports:
      - '9013:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    container_name: lms_app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '9014:3333'
    env_file:
      - .env.production
    # For production, we don't mount source code as a volume
    # This allows the container to use the built artifacts

volumes:
  postgres_data:
