@baseUrl = http://localhost:3333/api
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6eyJpZCI6IjUifSwiaWF0IjoxNzU4OTYxNjY5LCJleHAiOjE3NTg5Njg4Njl9.PUCm43puRgyMR440DtJ-9oOpnT-KXhgtczVv_o3wgGY



###? Get a user by id
GET {{baseUrl}}/users/5
Authorization: Bearer {{token}}



###? Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email" : "mahqwerty31@gmail.com",
  "password" : "faragfarag"
}


###? My profile
GET {{baseUrl}}/users/me
Authorization: Bearer {{token}}
Content-Type: application/json


###? Get all Users
GET {{baseUrl}}/users
Authorization: Bearer {{token}}
Content-Type: application/json



###############################################################

###? Create new user route
POST {{baseUrl}}/users
Content-Type: application/json

{
 "name": "test",
  "email": "test@test.com",
  "teacher_id": null,
  "password": "testtest",
  "role": "teacher",
  "phone": "+201111111111",
  "image": null,
  "active": true
}

###? SingUp api
POST {{baseUrl}}/auth/singup
Content-Type: application/json

{
   "name": "farag",
  "email": "mahqwerty31@gmail.com",
  "teacher_id": null,
  "password": "faragfarag",
  "role": "teacher",
  "phone": "+201111111111",
  "image": null,
  "active": true
}


###? Change password
PATCH {{baseUrl}}/users/changePassword
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword" :"qqwwee",
  "newPassword" : "faragfarag"
}

###? Forget password
POST {{baseUrl}}/users/forgetPassword
Content-Type: application/json 
 
{
  "email": "mahqwerty31@gmail.com"
}

###? Reset password
PUT {{baseUrl}}/users/resetPassword
Content-Type: application/json

{
  "resetToken": "40c57d77-b74e-4f6c-b0f1-d03bc59b8c29",
  "newPassword": "faragfarag"
}


